### ISSUE TITLE
TypeError: invalid type promotion

### ISSUE THREAD

**Issue by jmrichardson** [Automunge/AutoMunge#818]
Hi,

I am getting an error with a column data type timestamp:

```
_______________
Begin Automunge processing
evaluating column:  index
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-24482f45187e>", line 18, in <module>
    featureimportance, postprocess_dict = am.automunge(X_train_events)
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\Automunge\Automunger.py", line 30278, in automunge
    df_train = self.convert_inf_to_nan(df_train, column, category, postprocess_dict)
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\Automunge\Automunger.py", line 29484, in convert_inf_to_nan
    df[column] = np.where(df[column] == np.inf, np.nan, df[column])
  File "<__array_function__ internals>", line 6, in where
TypeError: invalid type promotion
```
The dataframe has datatype:

```
X_train_events.dtypes
Out[4]: 
index     datetime64[ns]
open             float64
high             float64
low              float64
close            float64
volume             int64
dtype: object
```

Also, the index column all have proper date/time stamps ie no NANs, or inf etc..

I am new to automunge so still trying to understand the package. Thanks for any help

**Comment by jmrichardson** [comment]
Doesn't work and no support
